[[commands]]
id = "jarvis_reboot"
type = "cli"
confirm = true
description = "Перезагрузка компьютера"
cli_cmd = "shutdown"
cli_args = ["/r", "/t", "0"]
sounds.ru = ["ok1", "ok2", "ok3"]
phrases.ru = [
    "перезагрузись",
    "перезагрузи себя",
    "выполни перезагрузку",
]


[[commands]]
id = "jarvis_insult"
type = "voice"
sounds.ru = ["stupid"]
phrases.ru = [
    "ты дурак",
    "ты дебил",
    "ты глупый",
    "ты тупой",
]


[[commands]]
id = "jarvis_thanks"
type = "voice"
sounds.ru = ["thanks"]
phrases.ru = [
    "спасибо",
    "молодец",
    "респект",
    "ты супер",
    "отличная работа",
    "ты крут",
    "ты большой молодец",
    "ты реально крут",
    "ты афигенный",
    "классная шутка",
    "очень смешно",
    "ты меня рассмешил",
    "веселая шутка",
    "смешной анекдот",
    "это было весело",
    "интересная шутка",
]


[[commands]]
id = "jarvis_joke"
type = "voice"
sounds.ru = ["joke1", "joke2", "joke3", "joke4", "joke5"]
phrases.ru = [
    "расскажи анекдот",
    "рассмеши",
    "пошути",
    "шутка",
    "расскажи шутку",
    "развесели меня",
    "что нибудь смешное",
    "подними мне настроение",
    "мне скучно",
    "хочу шутку",
    "хочу анекдот",
    "расскажи что нибудь смешное",
    "расскажи смешное что нибудь",
    "хочу посмеяться",
]
