#![allow(dead_code)]

use std::time::SystemTime;
use serde::{Deserialize, Serialize};

// ── Plan graph ────────────────────────────────────────────────────────────────

pub const MAX_PLAN_STEPS: usize = 5;

/// How two plan steps are connected.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EdgeKind {
    /// Step B starts after step A completes (regardless of outcome).
    Sequential,
    /// Step B starts only if step A succeeded.
    OnSuccess,
    /// Step B starts only if step A failed (recovery path).
    OnFailure,
    /// Step B can start concurrently with step A (not yet executed, reserved).
    Parallel,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanEdge {
    pub from: usize,   // index into PlanGraph::nodes
    pub to: usize,
    pub kind: EdgeKind,
}

/// Directed acyclic graph of plan steps.
///
/// `nodes` are PlanStep values; `edges` encode execution order and conditions.
/// Invariant: no cycles; `nodes.len() <= MAX_PLAN_STEPS`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanGraph {
    pub nodes: Vec<PlanStep>,
    pub edges: Vec<PlanEdge>,
    pub goal: String,
    pub origin: PlanOrigin,
    pub created_at_ms: u64,
}

impl PlanGraph {
    pub fn from_sequence(goal: impl Into<String>, steps: Vec<PlanStep>, origin: PlanOrigin) -> Self {
        let now = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let n = steps.len();
        let edges = (0..n.saturating_sub(1))
            .map(|i| PlanEdge { from: i, to: i + 1, kind: EdgeKind::Sequential })
            .collect();

        Self { nodes: steps, edges, goal: goal.into(), origin, created_at_ms: now }
    }

    pub fn step_count(&self) -> usize { self.nodes.len() }

    pub fn successors(&self, idx: usize, prev_success: bool) -> Vec<usize> {
        self.edges.iter()
            .filter(|e| e.from == idx && match e.kind {
                EdgeKind::Sequential => true,
                EdgeKind::OnSuccess  => prev_success,
                EdgeKind::OnFailure  => !prev_success,
                EdgeKind::Parallel   => true,
            })
            .map(|e| e.to)
            .collect()
    }
}

/// Where a plan was produced.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PlanOrigin {
    /// Hard-coded rule (deterministic, no LLM).
    RuleBased,
    /// Generated by the local LLM advisor (must pass containment before execution).
    LlmGenerated,
}

// ── Plan validator ────────────────────────────────────────────────────────────

#[derive(Debug)]
pub struct PlanValidationError(pub String);

pub struct PlanValidator;

impl PlanValidator {
    /// Validate a PlanGraph before any step is executed.
    /// Returns `Ok(())` or `Err(PlanValidationError)` on the first violation found.
    pub fn validate(graph: &PlanGraph) -> Result<(), PlanValidationError> {
        // V1: step count
        if graph.nodes.is_empty() {
            return Err(PlanValidationError("plan has zero steps".into()));
        }
        if graph.nodes.len() > MAX_PLAN_STEPS {
            return Err(PlanValidationError(format!(
                "plan exceeds MAX_PLAN_STEPS ({} > {})",
                graph.nodes.len(), MAX_PLAN_STEPS
            )));
        }

        // V2: all edge indices are in-bounds
        let n = graph.nodes.len();
        for edge in &graph.edges {
            if edge.from >= n || edge.to >= n {
                return Err(PlanValidationError(format!(
                    "edge ({},{}) out of bounds for {} nodes",
                    edge.from, edge.to, n
                )));
            }
        }

        // V3: no self-loops
        for edge in &graph.edges {
            if edge.from == edge.to {
                return Err(PlanValidationError(format!("self-loop at node {}", edge.from)));
            }
        }

        // V4: DAG check via DFS (back-edge detection)
        if Self::has_cycle(graph) {
            return Err(PlanValidationError("plan graph contains a cycle".into()));
        }

        // V5: all steps have non-empty command text
        for (i, step) in graph.nodes.iter().enumerate() {
            if step.command_text.trim().is_empty() {
                return Err(PlanValidationError(format!("step {} has empty command_text", i)));
            }
        }

        Ok(())
    }

    fn has_cycle(graph: &PlanGraph) -> bool {
        let n = graph.nodes.len();
        let mut visited = vec![0u8; n]; // 0=unvisited, 1=in-stack, 2=done

        fn dfs(node: usize, graph: &PlanGraph, visited: &mut Vec<u8>) -> bool {
            visited[node] = 1;
            for edge in &graph.edges {
                if edge.from == node {
                    if visited[edge.to] == 1 { return true; }
                    if visited[edge.to] == 0 && dfs(edge.to, graph, visited) { return true; }
                }
            }
            visited[node] = 2;
            false
        }

        for i in 0..n {
            if visited[i] == 0 && dfs(i, graph, &mut visited) {
                return true;
            }
        }
        false
    }
}

// ── Execution boundary ────────────────────────────────────────────────────────

/// Enforced boundary: the planner NEVER executes; execution NEVER plans.
///
/// A `PlanExecutionBoundary` value is produced by the planner and consumed
/// by the executor. It cannot be created outside this module, ensuring that
/// every plan passed to the executor was produced by the planner and validated.
pub struct PlanExecutionBoundary {
    pub graph: PlanGraph,
}

impl PlanExecutionBoundary {
    /// Only callable from within the planner module.
    pub(crate) fn seal(graph: PlanGraph) -> Self {
        Self { graph }
    }
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum StepStatus {
    Pending,
    Running,
    Success,
    Failed { reason: String },
    Skipped,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub description: String,
    pub command_text: String,
    pub status: StepStatus,
}

impl PlanStep {
    pub fn new(description: impl Into<String>, command_text: impl Into<String>) -> Self {
        Self {
            description: description.into(),
            command_text: command_text.into(),
            status: StepStatus::Pending,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskPlan {
    pub goal: String,
    pub steps: Vec<PlanStep>,
    pub current: usize,
    pub created_at_ms: u64,
}

impl TaskPlan {
    /// Build a single-step plan (the common case).
    pub fn single(goal: impl Into<String>, command_text: impl Into<String>) -> Self {
        let goal_str: String = goal.into();
        let cmd_str: String = command_text.into();
        Self {
            steps: vec![PlanStep::new(goal_str.clone(), cmd_str)],
            goal: goal_str,
            current: 0,
            created_at_ms: now_ms(),
        }
    }

    pub fn is_complete(&self) -> bool {
        self.current >= self.steps.len()
    }

    pub fn current_step(&self) -> Option<&PlanStep> {
        self.steps.get(self.current)
    }

    pub fn current_step_mut(&mut self) -> Option<&mut PlanStep> {
        self.steps.get_mut(self.current)
    }

    pub fn advance(&mut self) {
        self.current += 1;
    }

    pub fn mark_current_success(&mut self) {
        if let Some(step) = self.current_step_mut() {
            step.status = StepStatus::Success;
        }
        self.advance();
    }

    pub fn mark_current_failed(&mut self, reason: impl Into<String>) {
        if let Some(step) = self.current_step_mut() {
            step.status = StepStatus::Failed { reason: reason.into() };
        }
    }

    pub fn step_descriptions(&self) -> Vec<String> {
        self.steps.iter().map(|s| s.description.clone()).collect()
    }

    pub fn success_count(&self) -> usize {
        self.steps.iter().filter(|s| s.status == StepStatus::Success).count()
    }
}
