//! Autonomous Planner V2 — decomposes goals into verified execution plans.
//!
//! Builds on the Phase 12 `TaskGraph` and adds:
//!   - Risk estimation per node
//!   - Rollback node generation
//!   - Verification step injection
//!   - Prerequisite validation
//!
//! The planner NEVER executes.  It produces `ExecutionPlanV2` values that are
//! consumed by the executor after verification.

use std::sync::atomic::{AtomicU64, Ordering};
use std::collections::HashMap;

use crate::task_graph::{TaskGraph, TaskNode};
use crate::tool_capabilities::{get as get_profile};

pub static PLANS_CREATED:    AtomicU64 = AtomicU64::new(0);
pub static PLANS_FAILED:     AtomicU64 = AtomicU64::new(0);
pub static PLANS_ROLLED_BACK: AtomicU64 = AtomicU64::new(0);

pub const MAX_PLAN_NODES_V2: usize = 16;

// ── Risk estimate ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, serde::Serialize)]
pub struct RiskEstimate {
    pub overall:             String, // "low" | "medium" | "high" | "critical"
    pub high_risk_node_ids:  Vec<String>,
    pub requires_confirmation: bool,
    pub irreversible_node_ids: Vec<String>,
}

// ── Execution plan V2 ─────────────────────────────────────────────────────────

pub struct ExecutionPlanV2 {
    pub id:                   u64,
    pub goal:                 String,
    pub graph:                TaskGraph,
    /// IDs of nodes that are rollback actions (auto-generated by planner).
    pub rollback_node_ids:    Vec<String>,
    /// IDs of nodes that are verification steps (auto-generated by planner).
    pub verification_node_ids: Vec<String>,
    pub risk_estimate:        RiskEstimate,
}

impl ExecutionPlanV2 {
    pub fn step_count(&self) -> usize {
        self.graph.node_count()
    }

    pub fn has_rollback(&self) -> bool {
        !self.rollback_node_ids.is_empty()
    }

    pub fn has_verification(&self) -> bool {
        !self.verification_node_ids.is_empty()
    }
}

// ── Plan error ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, serde::Serialize)]
pub struct PlanError {
    pub reason: String,
}

impl PlanError {
    fn new(reason: impl Into<String>) -> Self {
        Self { reason: reason.into() }
    }
}

// ── Plan step specification ───────────────────────────────────────────────────

/// Input to the planner: one intended step.
#[derive(Debug, Clone)]
pub struct PlanStepSpec {
    pub tool_id: String,
    pub arg:     String,
    pub description: String,
}

impl PlanStepSpec {
    pub fn new(tool_id: impl Into<String>, arg: impl Into<String>, description: impl Into<String>) -> Self {
        Self {
            tool_id: tool_id.into(),
            arg: arg.into(),
            description: description.into(),
        }
    }
}

// ── Planner V2 ────────────────────────────────────────────────────────────────

pub struct AutonomousPlannerV2;

static PLAN_ID_SEQ: AtomicU64 = AtomicU64::new(1);

impl AutonomousPlannerV2 {
    /// Build an `ExecutionPlanV2` from a goal description and step specs.
    ///
    /// Steps are validated against the capability registry.
    /// Rollback nodes are injected for non-readonly side-effecting steps.
    /// Verification nodes are injected after each step.
    pub fn plan(
        goal: impl Into<String>,
        steps: Vec<PlanStepSpec>,
    ) -> Result<ExecutionPlanV2, PlanError> {
        let goal = goal.into();

        if steps.is_empty() {
            PLANS_FAILED.fetch_add(1, Ordering::Relaxed);
            return Err(PlanError::new("plan has zero steps"));
        }

        // Pre-validate: check tools exist in capability registry.
        for spec in &steps {
            if get_profile(&spec.tool_id).is_none() {
                PLANS_FAILED.fetch_add(1, Ordering::Relaxed);
                return Err(PlanError::new(format!(
                    "unknown tool '{}' — cannot plan for unregistered capability",
                    spec.tool_id
                )));
            }
        }

        let mut graph = TaskGraph::new();
        let mut rollback_node_ids = Vec::new();
        let mut verification_node_ids = Vec::new();
        let mut prev_id: Option<String> = None;

        for (i, spec) in steps.iter().enumerate() {
            let node_id = format!("step_{}", i);
            let deps = prev_id.iter().cloned().collect::<Vec<_>>();

            let node = TaskNode::new(
                &node_id,
                &spec.description,
                &spec.tool_id,
                &spec.arg,
            ).with_deps(deps);

            graph.add(node).map_err(|e| {
                PLANS_FAILED.fetch_add(1, Ordering::Relaxed);
                PlanError::new(e)
            })?;

            // Inject verification node after this step.
            let verify_id = format!("verify_{}", i);
            let verify_node = TaskNode::new(
                &verify_id,
                &format!("verify: {}", spec.description),
                "system.verify",
                &node_id,
            ).with_deps(vec![node_id.clone()]);

            graph.add(verify_node).map_err(|e| {
                PLANS_FAILED.fetch_add(1, Ordering::Relaxed);
                PlanError::new(e)
            })?;
            verification_node_ids.push(verify_id.clone());

            // Inject rollback node for non-readonly tools.
            if let Some(profile) = get_profile(&spec.tool_id) {
                if !profile.side_effect.is_reversible() {
                    let rollback_id = format!("rollback_{}", i);
                    let rollback_node = TaskNode::new(
                        &rollback_id,
                        &format!("rollback: {}", spec.description),
                        "system.rollback",
                        &node_id,
                    );
                    graph.add(rollback_node).map_err(|e| {
                        PLANS_FAILED.fetch_add(1, Ordering::Relaxed);
                        PlanError::new(e)
                    })?;
                    rollback_node_ids.push(rollback_id);
                }
            }

            prev_id = Some(verify_id);
        }

        let risk_estimate = Self::estimate_risk(&steps);
        let id = PLAN_ID_SEQ.fetch_add(1, Ordering::Relaxed);
        PLANS_CREATED.fetch_add(1, Ordering::Relaxed);

        Ok(ExecutionPlanV2 {
            id,
            goal,
            graph,
            rollback_node_ids,
            verification_node_ids,
            risk_estimate,
        })
    }

    fn estimate_risk(steps: &[PlanStepSpec]) -> RiskEstimate {
        let mut high_risk = Vec::new();
        let mut irreversible = Vec::new();
        let mut requires_confirmation = false;
        // Ordered: low < medium < high < critical
        let risk_rank = |s: &str| match s {
            "critical" => 3u8,
            "high"     => 2,
            "medium"   => 1,
            _          => 0,
        };
        let mut max_rank: u8 = 0;

        for (i, spec) in steps.iter().enumerate() {
            if let Some(profile) = get_profile(&spec.tool_id) {
                let level = profile.risk_level.as_str();
                let rank = risk_rank(level);
                if rank >= 2 {
                    high_risk.push(format!("step_{}", i));
                }
                if profile.irreversible {
                    irreversible.push(format!("step_{}", i));
                }
                if profile.requires_confirmation {
                    requires_confirmation = true;
                }
                if rank > max_rank { max_rank = rank; }
            }
        }

        let overall = match max_rank {
            3 => "critical",
            2 => "high",
            1 => "medium",
            _ => "low",
        };

        RiskEstimate {
            overall: overall.to_string(),
            high_risk_node_ids: high_risk,
            requires_confirmation,
            irreversible_node_ids: irreversible,
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tool_runtime;

    fn open_step() -> PlanStepSpec {
        PlanStepSpec::new(tool_runtime::TOOL_APP_OPEN, "calculator", "open calculator")
    }

    #[test]
    fn empty_steps_returns_error() {
        let r = AutonomousPlannerV2::plan("test", vec![]);
        assert!(r.is_err());
    }

    #[test]
    fn single_step_plan_succeeds() {
        let r = AutonomousPlannerV2::plan("open calculator", vec![open_step()]);
        assert!(r.is_ok());
        let plan = r.unwrap();
        assert_eq!(plan.goal, "open calculator");
    }

    #[test]
    fn plan_has_verification_nodes() {
        let r = AutonomousPlannerV2::plan("open calculator", vec![open_step()]).unwrap();
        assert!(r.has_verification());
        assert!(!r.verification_node_ids.is_empty());
    }

    #[test]
    fn unknown_tool_returns_plan_error() {
        let spec = PlanStepSpec::new("jarvis.invented.hackOS", "payload", "hack");
        let r = AutonomousPlannerV2::plan("evil plan", vec![spec]);
        assert!(r.is_err());
    }

    #[test]
    fn multi_step_plan_respects_order() {
        let steps = vec![
            PlanStepSpec::new(tool_runtime::TOOL_APP_OPEN, "ide", "open IDE"),
            PlanStepSpec::new(tool_runtime::TOOL_SYSTEM_VOLUME, "30", "set volume"),
        ];
        let plan = AutonomousPlannerV2::plan("setup workspace", steps).unwrap();
        assert!(plan.step_count() >= 2);
    }

    #[test]
    fn plans_created_counter_increments() {
        let before = PLANS_CREATED.load(Ordering::Relaxed);
        AutonomousPlannerV2::plan("test", vec![open_step()]).ok();
        assert!(PLANS_CREATED.load(Ordering::Relaxed) > before);
    }

    #[test]
    fn risk_estimate_is_low_for_safe_tools() {
        let plan = AutonomousPlannerV2::plan("test", vec![open_step()]).unwrap();
        assert_eq!(plan.risk_estimate.overall, "low");
        assert!(!plan.risk_estimate.requires_confirmation);
    }
}
