[[commands]]
id = "steam_open"
type = "lua"
script = "open.lua"
sandbox = "standard"
sounds.ru = ["game_mode"]
phrases.ru = [
    "включи игровой режим",
    "перейди в игровой режим",
    "я хочу поиграть",
    "включи стим",
    "запусти стим",
    "открой стим",
]


[[commands]]
id = "steam_close"
type = "lua"
script = "close.lua"
sandbox = "full"
sounds.ru = ["ok1", "ok2", "ok3", "ok4"]
phrases.ru = [
    "рабочий режим",
    "вернись в рабочий режим",
    "отключи игровой режим",
    "выйди из игрового режима",
    "выход с игрового режима",
    "рабочее пространство",
    "выключи игровой режим",
    "выключи стим",
    "отключи стим",
    "выйди из стима",
    "закрой стим",
]
